.PHONY: clean All

All:
	@echo "----------Building project:[ DwarfDig - Release ]----------"
	@"$(MAKE)" -f  "DwarfDig.mk" ../src/Precompiled.h.gch && "$(MAKE)" -f  "DwarfDig.mk"
clean:
	@echo "----------Cleaning project:[ DwarfDig - Release ]----------"
	@"$(MAKE)" -f  "DwarfDig.mk" clean
